### ISSUE TITLE
您好，GoogleDrive的数据集中，有关标签的图全是黑图(无信息)

### ISSUE THREAD

**Issue by liujinpen** [tist0bsc/SGCN#3]
您好，我阅读了论文，下载了文中提到的数据集发现有关label的文件夹中全是纯黑图，请问可以麻烦补一下吗，非常感谢！

**Comment by tist0bsc** [comment]
为了方便大家跑代码，我处理成二值图了，只有两个值，0是背景，1是道路，这样可以直接当label，不用后续处理。由于灰度0和灰度1肉眼辨别不出来，所以你看的就是全黑图。你可以写个代码，随便读一张图，转成数组，再乘个255进行保存，这样肉眼就可以辨别了

**Comment by tist0bsc** [comment]
> 您好，我阅读了论文，下载了文中提到的数据集发现有关label的文件夹中全是纯黑图，请问可以麻烦补一下吗，非常感谢！

为了方便大家跑代码，我处理成二值图了，只有两个值，0是背景，1是道路，这样可以直接当label，不用后续处理。由于灰度0和灰度1肉眼辨别不出来，所以你看的就是全黑图。你可以写个代码，随便读一张图，转成数组，再乘个255进行保存，这样肉眼就可以辨别了

**Comment by liujinpen** [comment]
好的，感谢解答！
