### ISSUE TITLE
A question about Massachusetts roads dataset

### ISSUE THREAD

**Issue by 567567l** [tist0bsc/SGCN#4]
The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”.
Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method?

**Comment by tist0bsc** [comment]
Yes, it must be cropped

**Comment by tist0bsc** [comment]
> The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”. Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method?

Yes, it must be cropped

**Comment by 567567l** [comment]
> 
Can you share the code of this part please?

**Comment by 567567l** [comment]
Can you share the code of this part please?
&nbsp;


1433858213
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月25日(星期六) 中午1:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tist0bsc/SGCN] A question about Massachusetts roads dataset (Issue #4)





  
The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”. Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method?
  
Yes, it must be cropped

**Comment by tist0bsc** [comment]
> Can you share the code of this part please? &nbsp; 1433858213 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月25日(星期六) 中午1:11 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [tist0bsc/SGCN] A question about Massachusetts roads dataset (Issue #4) The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”. Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method? Yes, it must be cropped — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

import os
import random
from time import sleep
from PIL import Image


class Parameters():
    def __init__(self):
        self.input_dir = 'val_labels/'  # 大图
        self.output_dir = 'val_224_label_cut/'  # 裁剪输出
        self.image_height = 224
        self.image_width = 224

para = Parameters()


def main():
    sleep(random.random())

    op_dir = para.output_dir
    if not os.path.exists(op_dir):
        os.makedirs(op_dir)
   
    img_num=0
    for each_image in os.listdir(para.input_dir):
        # 每个图像全路径
        image_fullpath = para.input_dir + '/' + each_image
        filename = os.path.splitext(os.path.split(image_fullpath)[1])[0]
        # PIL库打开每一张图像
        img = Image.open(image_fullpath)
        # 偏移量
        dx = para.image_width
        dy = para.image_height
        n = 0
        x1 = 0
        y1 = 0
        x2 = dx
        y2 = dy
        [X_Width, Y_Height] = img.size
        #print(img.size)
        # 纵向
        while (x1 + dx) <= X_Width:
            # 横向切
            while (y1 + dy) <= Y_Height:
                output_img = op_dir + filename + str(n) + ".png"
                n = n + 1
                #print ("num:%d , left:%d , up: %d , right:%d , below:%d" %(n ,x1 ,y1 ,x2 ,y2))
                im2 = img.crop((x1, y1, x2, y2))
                im2.save(output_img)
                
                y1 = y1 + dy
                y2 = y1 + dy
                if y2 > 1500:
                    output_img = op_dir + filename + str(n) + ".png"
                    n = n + 1
                    im2= img.crop((x1,1500-dy,x2,1500))
                    im2.save(output_img)
                    
            x1 = x1 + dx
            x2 = x1 + dx
            y1 = 0
            y2 = dy
            if x2 >1500:

                while (y1 + dy) <= Y_Height:
                    output_img = op_dir + filename + str(n) + ".png"
                    n = n + 1
                    #print ("num:%d , left:%d , up: %d , right: %d , below: %d" %(n ,x1 ,y1 ,x2 ,y2))
                    im2 = img.crop((1500-dx, y1, 1500, y2))
                    im2.save(output_img)
                    
                    y1 = y1 + dy
                    y2 = y1 + dy
                    if y2 > 1500:
                        output_img = op_dir + filename + str(n) + ".png"
                        n = n + 1
                        im2= img.crop((1500-dx,1500-dy,1500,1500))
                        im2.save(output_img)
        img_num=img_num+1
        print("img_no:%d , current_no:%d" %(img_num,n))

if __name__ == '__main__':
    main()

**Comment by tist0bsc** [comment]
> Can you share the code of this part please? &nbsp; 1433858213 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月25日(星期六) 中午1:11 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [tist0bsc/SGCN] A question about Massachusetts roads dataset (Issue #4) The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”. Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method? Yes, it must be cropped — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

import os
import random
from time import sleep
from PIL import Image


class Parameters():
    def __init__(self):
        self.input_dir = 'val_labels/'  # 大图
        self.output_dir = 'val_224_label_cut/'  # 裁剪输出
        self.train_txt_dir = 'test_cut.txt' #裁剪路径输出txt
        self.image_height = 224
        self.image_width = 224

para = Parameters()


def main():
    sleep(random.random())

    op_dir = para.output_dir
    if not os.path.exists(op_dir):
        os.makedirs(op_dir)
    file = open(para.train_txt_dir, 'w')
    img_num=0
    for each_image in os.listdir(para.input_dir):
        # 每个图像全路径
        image_fullpath = para.input_dir + '/' + each_image
        filename = os.path.splitext(os.path.split(image_fullpath)[1])[0]
        # PIL库打开每一张图像
        img = Image.open(image_fullpath)
        # 偏移量
        dx = para.image_width
        dy = para.image_height
        n = 0
        # 左上角切割
        x1 = 0
        y1 = 0
        x2 = dx
        y2 = dy
        [X_Width, Y_Height] = img.size
        #print(img.size)
        # 纵向
        while (x1 + dx) <= X_Width:
            # 横向切
            while (y1 + dy) <= Y_Height:
                output_img = op_dir + filename + str(n) + ".png"
                n = n + 1
                #print ("num:%d , left:%d , up: %d , right:%d , below:%d" %(n ,x1 ,y1 ,x2 ,y2))
                im2 = img.crop((x1, y1, x2, y2))
                im2.save(output_img)
                file.write(output_img + '\n')
                y1 = y1 + dy
                y2 = y1 + dy
                if y2 > 1500:
                    output_img = op_dir + filename + str(n) + ".png"
                    n = n + 1
                    im2= img.crop((x1,1500-dy,x2,1500))
                    im2.save(output_img)
                    file.write(output_img + '\n')
            x1 = x1 + dx
            x2 = x1 + dx
            y1 = 0
            y2 = dy
            if x2 >1500:

                while (y1 + dy) <= Y_Height:
                    output_img = op_dir + filename + str(n) + ".png"
                    n = n + 1
                    #print ("num:%d , left:%d , up: %d , right: %d , below: %d" %(n ,x1 ,y1 ,x2 ,y2))
                    im2 = img.crop((1500-dx, y1, 1500, y2))
                    im2.save(output_img)
                    file.write(output_img + '\n')
                    y1 = y1 + dy
                    y2 = y1 + dy
                    if y2 > 1500:
                        output_img = op_dir + filename + str(n) + ".png"
                        n = n + 1
                        im2= img.crop((1500-dx,1500-dy,1500,1500))
                        im2.save(output_img)
                        file.write(output_img + '\n')
        img_num=img_num+1
        print("img_no:%d , current_no:%d" %(img_num,n))

if __name__ == '__main__':
    main()

**Comment by tist0bsc** [comment]
import os
import random
from time import sleep
from PIL import Image


class Parameters():
    def __init__(self):
        self.input_dir = 'val_labels/'  # 大图
        self.output_dir = 'val_224_label_cut/'  # 裁剪输出
        self.image_height = 224
        self.image_width = 224

para = Parameters()


def main():
    sleep(random.random())

    op_dir = para.output_dir
    if not os.path.exists(op_dir):
        os.makedirs(op_dir)
    
    img_num=0
    for each_image in os.listdir(para.input_dir):
        # 每个图像全路径
        image_fullpath = para.input_dir + '/' + each_image
        filename = os.path.splitext(os.path.split(image_fullpath)[1])[0]
        # PIL库打开每一张图像
        img = Image.open(image_fullpath)
        # 偏移量
        dx = para.image_width
        dy = para.image_height
        n = 0
        # 左上角切割
        x1 = 0
        y1 = 0
        x2 = dx
        y2 = dy
        [X_Width, Y_Height] = img.size
        #print(img.size)
        # 纵向
        while (x1 + dx) <= X_Width:
            # 横向切
            while (y1 + dy) <= Y_Height:
                output_img = op_dir + filename + str(n) + ".png"
                n = n + 1
                #print ("num:%d , left:%d , up: %d , right:%d , below:%d" %(n ,x1 ,y1 ,x2 ,y2))
                im2 = img.crop((x1, y1, x2, y2))
                im2.save(output_img)
                
                y1 = y1 + dy
                y2 = y1 + dy
                if y2 > 1500:
                    output_img = op_dir + filename + str(n) + ".png"
                    n = n + 1
                    im2= img.crop((x1,1500-dy,x2,1500))
                    im2.save(output_img)
                   
            x1 = x1 + dx
            x2 = x1 + dx
            y1 = 0
            y2 = dy
            if x2 >1500:

                while (y1 + dy) <= Y_Height:
                    output_img = op_dir + filename + str(n) + ".png"
                    n = n + 1
                    #print ("num:%d , left:%d , up: %d , right: %d , below: %d" %(n ,x1 ,y1 ,x2 ,y2))
                    im2 = img.crop((1500-dx, y1, 1500, y2))
                    im2.save(output_img)
                   
                    y1 = y1 + dy
                    y2 = y1 + dy
                    if y2 > 1500:
                        output_img = op_dir + filename + str(n) + ".png"
                        n = n + 1
                        im2= img.crop((1500-dx,1500-dy,1500,1500))
                        im2.save(output_img)
                       
        img_num=img_num+1
        print("img_no:%d , current_no:%d" %(img_num,n))

if __name__ == '__main__':
    main()

**Comment by tist0bsc** [comment]
[imgcut.docx](https://github.com/tist0bsc/SGCN/files/11068078/imgcut.docx)

**Comment by tist0bsc** [comment]
> Can you share the code of this part please? &nbsp; 1433858213 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月25日(星期六) 中午1:11 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [tist0bsc/SGCN] A question about Massachusetts roads dataset (Issue #4) The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”. Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method? Yes, it must be cropped — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

[imgcut.docx](https://github.com/tist0bsc/SGCN/files/11068079/imgcut.docx)

**Comment by 567567l** [comment]
> > Can you share the code of this part please?   1433858213 _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2023年3月25日(星期六) 中午1:11 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [tist0bsc/SGCN] A question about Massachusetts roads dataset (Issue #4) The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”. Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method? Yes, it must be cropped — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> [imgcut.docx](https://github.com/tist0bsc/SGCN/files/11068079/imgcut.docx)

I have another question, when running the predict_road file, is it correct to input the cropped image directly and then stitch the predicted result to the original size? Or can I just input the original image？

**Comment by tist0bsc** [comment]
> input the cropped image directly and then stitch the predicted result to the original size

input the cropped image directly and then merge to the original size
 This part of the code is basic, and it is suggest that you code it by yourself next time 
[img_merge.docx](https://github.com/tist0bsc/SGCN/files/11068113/img_merge.docx)

**Comment by tist0bsc** [comment]
> > > Can you share the code of this part please?   1433858213 _**@**_.***  
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2023年3月25日(星期六) 中午1:11 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [tist0bsc/SGCN] A question about Massachusetts roads dataset (Issue #4) The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”. Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method? Yes, it must be cropped — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > [imgcut.docx](https://github.com/tist0bsc/SGCN/files/11068079/imgcut.docx)
> 
> I have another question, when running the predict_road file, is it correct to input the cropped image directly and then stitch the predicted result to the original size? Or can I just input the original image？

Input the cropped image directly and then merge to the original size

This part of the code is relatively simple, and it is suggest that you code it by yourself next time.
[img_merge.docx](https://github.com/tist0bsc/SGCN/files/11068119/img_merge.docx)

**Comment by 567567l** [comment]
> > > > Can you share the code of this part please?   1433858213 _**@**_.***
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2023年3月25日(星期六) 中午1:11 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [tist0bsc/SGCN] A question about Massachusetts roads dataset (Issue #4) The paper mentions：“To increase the training efficiency of the proposed model,each original image and label map was divided into small batches, in the direction of height and width, with sizes of 224 × 224 and 512 × 512 pixels”. Does it mean that the original image is cropped to equal block size and saved before being input to the model? Or is there another method? Yes, it must be cropped — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > > 
> > > 
> > > [imgcut.docx](https://github.com/tist0bsc/SGCN/files/11068079/imgcut.docx)
> > 
> > 
> > I have another question, when running the predict_road file, is it correct to input the cropped image directly and then stitch the predicted result to the original size? Or can I just input the original image？
> 
> Input the cropped image directly and then merge to the original size
> 
> This part of the code is relatively simple, and it is suggest that you code it by yourself next time. [img_merge.docx](https://github.com/tist0bsc/SGCN/files/11068119/img_merge.docx)

Thank you for your help! I will try to code it by myself.
